install.packages("ggplot2")       
install.packages("GGally")
library("ggplot2")                     
library("GGally")
str(mtcars)
mtcars$am <- gsub("0", "auto", mtcars$am)
mtcars$am <- gsub("1", "manual", mtcars$am)
mtcars$am <- factor(mtcars$am)
mtcars$vs <- factor(mtcars$vs)
mtcars$gear <- factor(mtcars$gear)
mtcars$carb <- factor(mtcars$carb)
t.test(mpg ~ am, mtcars)
am_model <- lm(mpg ~ am, mtcars)
summary(am_model)
full_model <- lm(mpg ~ ., mtcars)
summary(full_model)
step_model <- step(full_model, direction = "backward", trace = FALSE)
summary(step_model)
confint(step_model)['ammanual', ]
par(mfrow = c(2,2))
plot(step_model)
data(mtcars)
mtcars$am <- factor(mtcars$am)
ggpairs(mtcars, mapping = aes(colour = am))
